version: '3.9'

services:

  db-ui:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@cracker-db:27017/
    depends_on:
        - cracker-db

  cracker-db:
    image: mongo
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME: admin"
      - "MONGO_INITDB_ROOT_PASSWORD: admin"
      - "MONGO_INITDB_DATABASE : cracker"
    ports:
        - 27017:27017
    volumes:
      - cracker-db:/data/db

volumes:
  cracker-db: