version: '3.9'

services:

  db-ui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@cracker-db:27017/
    depends_on:
        - cracker-db

  cracker-db:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=password_cracker
    ports:
        - 27017:27017
    volumes:
      - cracker-db:/data/db

volumes:
  cracker-db: